### ISSUE TITLE
DaggerAppComponent类未找到

### ISSUE THREAD

**Issue by wxmylife** [Dimon94/GanWuMei#14]
package com.dimon.ganwumei.injector.components包下类未找到，MyApplication类报错

**Comment by Dimon94** [comment]
DaggerAppComponent这个类是生成的，所以需要先编译才能找到。

**Comment by Dimon94** [comment]
@wxmylife DaggerAppComponent这个类是生成的，所以需要先编译才能找到。

**Comment by wxmylife** [comment]
因为我之前没接触过dagger依赖注入，这个是因为这个的原因吗？

**Comment by Dimon94** [comment]
恩恩，你可以编译多几次，生成DaggerAppComponent这类文件之后才会编译成功的。还有一个小问题是我平常调试都会遇到的坑，就是更改了一下Dagger的那些相关文件，要重新生成。也会报DaggerAppComponent类未找到子类的错误，这时就需要找到原来的生成文件，然后删除后重新生成才行。这个问题我也不知道怎么解决，Dagger2我也是刚学的。

**Comment by wxmylife** [comment]
恩恩  好的  其实我觉得你可以在你项目中用到mvp或者MVVM  那就更完美了

**Comment by Dimon94** [comment]
@wxmylife 说实话，有尝试过MVP，但是时间不够充裕，重构起来有点费时间，毕竟还得找工作呀！！！要毕业了没工作很不踏实哎呀。之后应该会弄MVP，毕竟之前还看了很多官方那个MVP，不搞总是觉得不爽。

**Comment by wxmylife** [comment]
我觉的很好啊 ，虽然写起来麻烦，但是维护起来满方便的  你也是大四学生吗

**Comment by Dimon94** [comment]
@wxmylife 大四学生呢。MVP的确很好~维护起代码没那么辛苦，找到工作后就把MVP加进去。

**Comment by wxmylife** [comment]
同为大四学生，只不过我比你好点 ，已经上班快一年多了

**Comment by Dimon94** [comment]
@wxmylife 厉害~
